### ISSUE TITLE
Failing on Ryzen 1800x system

### ISSUE THREAD

**Issue by vt116** [matej137/OutlookRemover#4]
Not sure what's going on here - if you can shed some light on it or possibly fix the app if needed, it would be amazing.
![Screenshot (9)](https://github.com/user-attachments/assets/7cba06e4-d9bd-47ce-af47-55afb8da1c3d)

This really is a huge timesaving program by the way. Thank you so much for making it.

**Comment by matej137** [comment]
Thank you for the report, I'll take a look on it. 
But it looks like the thing that's failing is the uninstallation of the original new outlook, which might be caused by it just not being present. But I'll have to actually confirm that.

It also does not necessarily mean that the script did not work (you can check if it did by going to settings > apps > outlook (new). If it's there and takes up +/- 8kb, it's working). But I can't really tell you that with absolute certainty.

Also, I'm glad that you find it useful. And hopefully, we'll get those issues sorted.

**Comment by matej137** [comment]
Looking at the screenshot more closely, it appears that you are not running the original version of the script, but a fork instead. Please download my version from the releases page and try again.

If the issue persists, remove the original new outlook manually (step by step instructions are in the new readme). If any further issues arise, please let me know

Hope this helps!

**Comment by vt116** [comment]
Hello,
Thank you so much for examining this.

On this older version, I tried your 0.9 version, and then @SempaiRock's forked version, and neither works. However, I also tried your version on a newer x64 system and it did not work, but @SempaiRock's version did, so I think your version needs to be updated for whatever changes Sempai has made.

**Comment by matej137** [comment]
Thank you for the info, I'll look into it further

**Comment by vt116** [comment]
Thanks for your help on the ARM64 issue.

I'll try the manual installation on this system, with your script, when I get home.

**Comment by matej137** [comment]
Okay, but I have changed the .bat file slightly, so please download the latest version again. Hopefully, it should all work now

**Comment by vt116** [comment]
Yes, it works!

I think the reason it didn't work was because on this system, there are 3 users. The original admin account transferred admin to another user. When I ran the script on the original admin account instead of the new admin account, it worked successfully.

This must mean Windows apps are created only for the original admin. I wonder what would happen if I deleted that user from the system?
